# Generated by Django 4.1.7 on 2023-02-27 12:05

from django.db import migrations, models
import teacher.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя учителя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия учителя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[teacher.utils.validate_phone_namber], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
