# Generated by Django 4.1.7 on 2023-02-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='klass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klass.klass', verbose_name='Класс учителя'),
            preserve_default=False,
        ),
    ]
