# Generated by Django 4.1.7 on 2023-02-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_student', models.CharField(max_length=30, verbose_name='Название урока')),
                ('surname_student', models.CharField(max_length=30, verbose_name='Начало урока')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/', verbose_name='Фото')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.klass', verbose_name='У какого класса урок')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
