# Generated by Django 4.1.7 on 2023-02-27 11:16

from django.db import migrations, models
import zavuch.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zavuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zavuch/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[zavuch.utils.validate_phone_namber], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Завуч',
                'verbose_name_plural': 'Завучи',
            },
        ),
    ]
