# Generated by Django 4.1.7 on 2023-02-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=30, verbose_name='Название урока')),
                ('time_lesson', models.CharField(max_length=5, verbose_name='Начало урока')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.klass', verbose_name='У какого класса урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
